output: catch_tests.o cpp_test.o
    g++ catch_tests.o cpp_test.o -o output

tests_main.o: tests_main.cpp
    g++ -c tests_main.cpp

catch_tests.o: catch_tests.cpp
    g++ -c catch_tests.cpp
    
functions_to_test.o: ../functions_to_test.cpp ../functions_to_test.h
    g++ -c ../functions_to_test.cpp

clean:
    rm *.o *.exe